### ISSUE TITLE
Carthage not working

### ISSUE THREAD

**Issue by inPhilly** [SDWebImage/SDWebImageLinkPlugin#7] opened 2019-12-31 05:11 UTC
Carthage does not appear to be working. Could you test to see if it is working, and add instructions?

**Comment by dreampiggy** [comment] 2019-12-31 10:16
Carthage Version ?

Seems I test it locally and works.

```
➜  LinkPluginTest git:(master) ✗ cat Cartfile
github "SDWebImage/SDWebImageLinkPlugin"%
➜  LinkPluginTest git:(master) ✗ carthage update --cache-builds
*** Cloning SDWebImageLinkPlugin
*** Fetching SDWebImage
*** Checking out SDWebImageLinkPlugin at "0.2.2"
*** Checking out SDWebImage at "5.4.1"
*** No cache found for SDWebImage, building with all downstream dependencies
*** xcodebuild output can be found in /var/folders/y4/_98b424x3jv54_1tbfvswjpm0000gn/T/carthage-xcodebuild.Se64uw.log
*** Building scheme "SDWebImage" in SDWebImage.xcodeproj
*** Building scheme "SDWebImageMapKit" in SDWebImage.xcodeproj
*** Building scheme "SDWebImageLinkPlugin-macOS" in SDWebImageLinkPlugin.xcodeproj
*** Building scheme "SDWebImageLinkPlugin" in SDWebImageLinkPlugin.xcodeproj
➜  LinkPluginTest git:(master) ✗ cat Cartfile.resolved
github "SDWebImage/SDWebImage" "5.4.1"
github "SDWebImage/SDWebImageLinkPlugin" "0.2.2"
```

---

I know, seems using the #import cause the compile issue, because the umbrella header `SDWebImageLinkPlugin.h` does not get updated. I'll fix it soon.

![image](https://user-images.githubusercontent.com/6919743/71618304-0d1c5380-2bfa-11ea-926f-69e544d6ccaa.png)

**Comment by dreampiggy** [comment] 2019-12-31 10:25
Fixed in [v0.2.3 version](https://github.com/SDWebImage/SDWebImageLinkPlugin/releases/tag/0.2.3), please update and have a try again.

![image](https://user-images.githubusercontent.com/6919743/71618530-e4488e00-2bfa-11ea-86b1-e7e27457fc49.png)

**Comment by inPhilly** [comment] 2020-01-02 03:39
Still no framework in Build/iOS folder for SDWebImageLinkPlugin, unfortunately : (

**Comment by dreampiggy** [comment] 2020-01-02 06:56
> Still no framework in Build/iOS folder for SDWebImageLinkPlugin, unfortunately : (

@inPhilly  ? What's the ouput and operation you use ? Please attach the comsole output and the Xcode compile screenshot ?

**Comment by inPhilly** [comment] 2020-01-02 19:33
I am saying that there is not a framework created in the Build/iOS folder for this plugin when I type “carthage update SDWebImageLinkPlugin” in the terminal while in the correct directory. All other Carthage frameworks are created/updated correctly. Should there be a framework created for the SDWebImageLinkPlugin in the Build/iOS folder for Carthage?

**Comment by dreampiggy** [comment] 2020-01-03 03:28
Run the command below in order, show me your ouput. I can not reproduce this problem on my local environment...


```
➜  Desktop mkdir LinkPluginTest
➜  Desktop cd LinkPluginTest
➜  LinkPluginTest echo 'github "SDWebImage/SDWebImageLinkPlugin"' > Cartfile
➜  LinkPluginTest carthage version
0.34.0
➜  LinkPluginTest carthage update --cache-builds
*** Fetching SDWebImageLinkPlugin
*** Fetching SDWebImage
*** Checking out SDWebImageLinkPlugin at "0.2.3"
*** Checking out SDWebImage at "5.4.1"
*** No cache found for SDWebImage, building with all downstream dependencies
*** xcodebuild output can be found in /var/folders/y4/_98b424x3jv54_1tbfvswjpm0000gn/T/carthage-xcodebuild.gd8XzO.log
*** Building scheme "SDWebImage" in SDWebImage.xcodeproj
*** Building scheme "SDWebImageMapKit" in SDWebImage.xcodeproj
*** Building scheme "SDWebImageLinkPlugin-macOS" in SDWebImageLinkPlugin.xcodeproj
*** Building scheme "SDWebImageLinkPlugin" in SDWebImageLinkPlugin.xcodeproj
➜  LinkPluginTest ls -lash Carthage/Build/iOS
total 536
  0 drwxr-xr-x  13 lizhuoli  staff   416B  1  3 11:25 .
  0 drwxr-xr-x   8 lizhuoli  staff   256B  1  3 11:25 ..
224 -rw-------   1 lizhuoli  staff   110K  1  3 11:24 266B2C55-CF68-3D00-B189-9843080F31B5.bcsymbolmap
232 -rw-------   1 lizhuoli  staff   113K  1  3 11:24 411C6030-147C-3492-917E-6D378C0F8307.bcsymbolmap
 32 -rw-------   1 lizhuoli  staff    14K  1  3 11:25 6655AC27-1DE0-3574-A21C-4081844A4CAA.bcsymbolmap
 24 -rw-------   1 lizhuoli  staff    11K  1  3 11:25 83782403-9471-3143-9BBE-6B42D703437B.bcsymbolmap
 24 -rw-------   1 lizhuoli  staff   9.2K  1  3 11:25 FE2D87D1-F90A-326C-BFC8-A8F88E87DDBC.bcsymbolmap
  0 drwxr-xr-x   7 lizhuoli  staff   224B  1  3 11:24 SDWebImage.framework
  0 drwxr-xr-x   3 lizhuoli  staff    96B  1  3 11:24 SDWebImage.framework.dSYM
  0 drwxr-xr-x   6 lizhuoli  staff   192B  1  3 11:25 SDWebImageLinkPlugin.framework
  0 drwxr-xr-x   3 lizhuoli  staff    96B  1  3 11:25 SDWebImageLinkPlugin.framework.dSYM
  0 drwxr-xr-x   6 lizhuoli  staff   192B  1  3 11:25 SDWebImageMapKit.framework
  0 drwxr-xr-x   3 lizhuoli  staff    96B  1  3 11:25 SDWebImageMapKit.framework.dSYM
```

**Comment by inPhilly** [comment] 2020-01-03 04:11
home SDWebImageLinkPluginTest % carthage version
0.34.0
home SDWebImageLinkPluginTest % carthage update --cache-builds 
*** Fetching SDWebImageLinkPlugin
*** Fetching SDWebImage
*** Checking out SDWebImageLinkPlugin at "0.2.3"
*** Checking out SDWebImage at "5.4.1"
*** No cache found for SDWebImage, building with all downstream dependencies
*** xcodebuild output can be found in /var/folders/v9/tnzdr8l17cz1xkpcq9l48h8c0000gq/T/carthage-xcodebuild.gGei8d.log
*** Building scheme "SDWebImage" in SDWebImage.xcodeproj
Could not find any available simulators for watchOS
home SDWebImageLinkPluginTest %

**Comment by dreampiggy** [comment] 2020-01-03 06:19
> Could not find any available simulators for watchOS

Seems you're using the wrong Xcode version ? Check your Xcode version to see the result. SDWebImage 5.0.0+ need Xcode 10, SDWebImageLinkPlugin need Xcode 11, so you need Xcode 11.

Or, therer may be some other issue not related to ourself, may because of Carthage itself (does they use some sub-dependency ?)

**Comment by dreampiggy** [comment] 2020-01-03 06:20
https://github.com/Carthage/Carthage/issues/2602

**Comment by inPhilly** [comment] 2020-01-04 04:31
I am using Xcode 11

**Comment by dreampiggy** [comment] 2020-01-04 04:46
You should fix your local environment firstlly. Seems your watchOS simulator is broken, see: https://gist.github.com/ZevEisenberg/5a172662cb576872d1ab

or, you can try to trash this folder and reboot the Mac.

```
~/Library/Developer/CoreSimulator
```

If this can not solve the problem, maybe it's something that Carthage's bug. My local environment is:

Xcode Version 11.2 (11B52)
macOS 10.15.1

**Comment by inPhilly** [comment] 2020-01-07 17:11
I got it working by adding WatchOS simulators to my Xcode. But, I did want to note - this Carthage framework is the only one that gave me issues for not having those simulators.

**Closed as completed** 2020-01-07 17:13 UTC
Labels: Carthage
